spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
# Database Connection
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/pavel
spring.datasource.username=postgres
spring.datasource.password=Xysvgh80

## Hibernate/JPA Properties
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true

# Debugging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
debug=true